# NumPy
Расммотрим как работать с библиотекой для вычислений NumPy.
Пройдемся по основным объектам, их методам.

У кого не установлен NumPy его необходимо установить:

<code>
$ pip install numpy
</code>

In [ ]:
!pip install numpy

In [70]:
import numpy as np

# Основы

Скаляр (Тензор / Матрица ранга 0):

In [71]:
scalar = 25
scalar

25

In [72]:
# Если нам необходим иной тип целочисленного значения (например int8, int16, uint8 ...) то нам необходимо уже использовать библиотеку NumPy
type(scalar)

int

In [73]:
scalar = np.int64(25)
scalar

25

In [74]:
type(scalar)

numpy.int64

### Вектор (Rank 1 Tensor)

In [75]:
# 1-dimensional array
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [76]:
# индексация по вектору
print(type(a))
print(a[0])
print(type(a[0]))

<class 'numpy.ndarray'>
1
<class 'numpy.int64'>


### Матрица

In [77]:
# 2-dimensional array
b = np.array([[1, 0.99, 0.09, 0.03],
              [12, 0.99, 0.52, 13],
              [22, -12.5, 0, 22]])

print(b)
print(type(b))

[[  1.     0.99   0.09   0.03]
 [ 12.     0.99   0.52  13.  ]
 [ 22.   -12.5    0.    22.  ]]
<class 'numpy.ndarray'>


### Тензор

In [78]:
# 3-dimensional array
c = np.array([[[1, 0.99, 0.09, 0.03],
              [12, 0.99, 0.52, 13],
              [22, -12.5, 0, 22]],

             [[0, 1.2, 1.9, 2.03],
              [12, 1.99, 1.52, 13],
              [2, -12.5, 0, 1]],

             [[1, 0.99, 0.09, 0.03],
              [12, 0.99, 0.52, 13],
              [22, -12.5, 0, 22]]])

print(c)
print(type(c))

[[[  1.     0.99   0.09   0.03]
  [ 12.     0.99   0.52  13.  ]
  [ 22.   -12.5    0.    22.  ]]

 [[  0.     1.2    1.9    2.03]
  [ 12.     1.99   1.52  13.  ]
  [  2.   -12.5    0.     1.  ]]

 [[  1.     0.99   0.09   0.03]
  [ 12.     0.99   0.52  13.  ]
  [ 22.   -12.5    0.    22.  ]]]
<class 'numpy.ndarray'>


In [79]:
# Получение размерности для объекта
print("Dimensions")
print("a: {}\nb: {}\nc: {}".format(a.ndim, b.ndim, c.ndim))

Dimensions
a: 1
b: 2
c: 3


In [80]:
# Получение формы ("размерности") объекта
print("Shapes")
print("a: {}\nb: {}\nc: {}".format(a.shape, b.shape, c.shape))

Shapes
a: (3,)
b: (3, 4)
c: (3, 3, 4)


In [81]:
# Тип данных в numpy array и занимаемая память
print("Data Type of a     : ",  a.dtype)
print("Item Size in bytes : ",  a.itemsize)
print("Size in bytes      : ",  a.size)
print("Total Size         : ",  a.nbytes)

Data Type of a     :  int64
Item Size in bytes :  8
Size in bytes      :  3
Total Size         :  24


In [82]:
# во время создания объекта мы можем указать какой тип целочисленных данных нам необходим
a = np.array([1, 2, 3], dtype='int8')
print(a)
print(type(a))
print(type(a[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [83]:
print("Data Type of a     : ", a.dtype)
print("Item Size in bytes : ",  a.itemsize)
print("Size in bytes      : ",  a.size)
print("Total Size         : ",  a.nbytes)

Data Type of a     :  int8
Item Size in bytes :  1
Size in bytes      :  3
Total Size         :  3


# Доступ, Индексация и Изменение определенных элементов массива

In [84]:
a = np.array([[1, 3, 5, 9, 10, 12, 15],
             [1, 2, 6, 10, 14, 18, 22],
             [1, 4, 8, 12, 16, 20, 24]])

print(a.ndim)
print(a.shape)

2
(3, 7)


In [85]:
# Как и любой другой объект последовательности, массивы NumPy поддерживают индексацию и срезы
print(a[1:3, 2:3]) # 1) 2-ая строка и 2-й и 3-й элементы 2) 3-я строка и 2-ой и 3-й элементы

[[6]
 [8]]


In [86]:
# Получение конкретного элемента [строка, столбец]
print("""
матрица: \n{}\n
a11 = {}
a22 = {}
a33 = {}
""".format(a, a[0, 0], a[1, 1], a[2, 2]))


матрица: 
[[ 1  3  5  9 10 12 15]
 [ 1  2  6 10 14 18 22]
 [ 1  4  8 12 16 20 24]]

a11 = 1
a22 = 2
a33 = 8



In [87]:
# Получение конкретной строки массива [строка, элементы строки]
print(a[0, :])

[ 1  3  5  9 10 12 15]


In [88]:
# Получение конкретного столбца массива
print(a[:, 1])

[3 2 4]


In [89]:
# [start:end:step] нарезка с шагом
print(a[0, 1:5:3])

[ 3 10]


# Инициализация различного рода массивов

In [90]:
# Нулевая матрица порядка n
print(np.zeros(shape=(5, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [91]:
np.zeros(shape=(5, 5))[0].dtype

dtype('float64')

In [92]:
# Матрица все элементы которой равны 1
print(np.ones(shape=(3,9), dtype='int32'))

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [93]:
# Матрица все эелементы которой равны указанному числу
print(np.full(shape=(5,10), fill_value=22, dtype='float16'))

[[22. 22. 22. 22. 22. 22. 22. 22. 22. 22.]
 [22. 22. 22. 22. 22. 22. 22. 22. 22. 22.]
 [22. 22. 22. 22. 22. 22. 22. 22. 22. 22.]
 [22. 22. 22. 22. 22. 22. 22. 22. 22. 22.]
 [22. 22. 22. 22. 22. 22. 22. 22. 22. 22.]]


In [94]:
# Построение аналогичной матрицы
a = np.ones(shape=(5,5), dtype='float32')

# Ссылаясь на объект выше мы можем построить аналогичный объект заполнив его своим значением
print(np.full_like(a, 0.25))

[[0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25]]


In [95]:
# Инициализация массива случайным набором значений из нормального распределения
print(np.random.rand(4,2))

[[0.67209286 0.02684479]
 [0.08674602 0.14397641]
 [0.21007368 0.62570804]
 [0.29238108 0.68595549]]


In [96]:
# Инициализация случайной матрицы целочисленных значений с нижней и верхней границей
print(np.random.randint(low=2, high=151, size=(10, 10)))

[[ 39 100  31  99  64 113  93 107   4  85]
 [114  55  49  97  64 108  39  11 144  54]
 [ 21  50  57  52 148 148  31 133  20  27]
 [ 87 122 104 146 121 105  95   7  51 117]
 [129  70  52 121 145  99  68  99  56  61]
 [ 23  75  84  51 100 122  50  88 123  59]
 [ 66 120  50  27  86  87 149  97  71  73]
 [112  46 112  45  93 126 150  40  75 103]
 [ 41 127  46  67  81  31 106  72  18 114]
 [141  54 117  71  21 102 121  20  30  66]]


In [97]:
# Единичная матрица размерность nxn
print(np.identity(n=10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Арифметические операции

In [98]:
a = np.random.randint(low=0, high=15, size=(1,12))
print(a)

[[ 1  3 10  8  5 14  8  0  7 12  9  9]]


In [100]:
# Складывается каждый элемент объекта
print(a + 3)

[[ 4  6 13 11  8 17 11  3 10 15 12 12]]


In [101]:
# Аналогично с вычитанием, умножением, делением и остальными арифметическими операциями
a - 3

array([[-2,  0,  7,  5,  2, 11,  5, -3,  4,  9,  6,  6]])

In [102]:
a * 3

array([[ 3,  9, 30, 24, 15, 42, 24,  0, 21, 36, 27, 27]])

In [103]:
a / 3

array([[0.33333333, 1.        , 3.33333333, 2.66666667, 1.66666667,
        4.66666667, 2.66666667, 0.        , 2.33333333, 4.        ,
        3.        , 3.        ]])

In [104]:
a ** 3

array([[   1,   27, 1000,  512,  125, 2744,  512,    0,  343, 1728,  729,
         729]])

In [105]:
b = np.random.randint(low=0, high=15, size=(1,20))

In [106]:
a

array([[ 1,  3, 10,  8,  5, 14,  8,  0,  7, 12,  9,  9]])

In [107]:
b

array([[ 2,  3, 12,  7,  4,  8, 14,  0,  8, 14, 14, 13,  1,  1,  2, 11,
         2, 14, 10,  1]])

In [108]:
# Мы не можем складывать вектора разной размерности
a + b

ValueError: operands could not be broadcast together with shapes (1,12) (1,20) 

# Примеры базовых операций линейной алгебры

In [109]:
a = np.random.randint(low=0, high=13, size=(5, 5))
b = np.random.randint(low=14, high=27, size=(5, 12))

# Операция умножения двух матриц
np.matmul(a, b)

array([[442, 518, 437, 583, 532, 528, 614, 580, 603, 497, 392, 559],
       [622, 603, 537, 778, 592, 693, 689, 640, 578, 622, 527, 569],
       [745, 793, 614, 935, 723, 824, 807, 801, 723, 790, 683, 746],
       [764, 883, 673, 985, 786, 875, 906, 847, 858, 814, 655, 830],
       [698, 783, 575, 876, 708, 781, 813, 792, 744, 764, 643, 767]])

In [110]:
# Аналогичная операция умножения 2-х матриц с использованием символа декоратора
a@b

array([[442, 518, 437, 583, 532, 528, 614, 580, 603, 497, 392, 559],
       [622, 603, 537, 778, 592, 693, 689, 640, 578, 622, 527, 569],
       [745, 793, 614, 935, 723, 824, 807, 801, 723, 790, 683, 746],
       [764, 883, 673, 985, 786, 875, 906, 847, 858, 814, 655, 830],
       [698, 783, 575, 876, 708, 781, 813, 792, 744, 764, 643, 767]])

In [111]:
# Нахождение определителя
c = np.identity(3)
np.linalg.det(c)

1.0

# Статистические операции

In [112]:
random_array = np.random.randint(low=0, high=12, size=(3,3))

In [113]:
random_array

array([[ 8,  8,  0],
       [ 1, 11,  2],
       [ 5,  9,  0]])

In [114]:
np.min(random_array)

0

In [115]:
np.max(random_array)

11

In [116]:
np.sum(random_array)

44

In [117]:
np.median(random_array)

5.0

In [118]:
np.average(random_array)

4.888888888888889

# Манипуляции с размерностями массивов

In [119]:
original = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Изменение формы матрицы, следует помнить что мы можем привести только к той размерности которая способна включать в себя 8 элементов (2х4, 4х2, 1х8, 8х1)
reshaped = np.reshape(original, newshape=(4,2))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [120]:
# Вертикальное объединения двух соразмерных массивов
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
# Горизонтально объединение двух соразмерных массивов
print(np.hstack([v1,v2]))

[1 2 3 4 5 6 7 8]


In [123]:
# Чтение числовых данных из файла
data = np.genfromtxt('../files/data.txt', delimiter=',').astype('int32')

In [124]:
data

array([[  1,   2,   3,  55, 120,  13,  91,  15,  16,  22,  35,  41,  51,
         76, 120,  23,  32],
       [  1,   1,   2,   3,   5, 756,  12,  20,  32,  52,  84, 136, 220,
        356, 120,  23,  32],
       [  0,   2,   3,   0, 120,  13,  12,  15,  16,  22,   0,  41, 999,
         76,  78,   0,  32]], dtype=int32)

#### Сравнение двух объектов

In [125]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [126]:
print(A)
print(B)

[0 0 0 1 0]
[1 1 0 0 1]


In [127]:
print(A == B)

[False False  True False False]


In [128]:
# Предполагает что массивы имеют идентичную форму и поэлементное сравнение значений
equal = np.allclose(A,B)
print(equal)

False


In [129]:
# Проверка как формы, так и значений элементов, без допусков (значения должны быть точно равными)
equal = np.array_equal(A,B)
print(equal)

False


Нормализация матрицы

In [130]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

# В старых версиях библиотеки реализован такой подход (будьте внимательны если будете читать легаси код какого-либо проекта)
# Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 1.61213490e-01  2.36700117e-01  2.97870079e-01  2.73440438e-01
  -4.58416753e-01 -4.08851813e-01 -2.00311000e-01  1.80785130e-01
  -2.66097261e-01  1.83667571e-01]
 [ 2.75198446e-01 -2.09388307e-01  9.42926677e-02 -3.75468986e-01
   7.93660117e-05 -6.30759801e-02  2.67735438e-01  2.44234852e-01
  -1.88028441e-01 -4.55790556e-02]
 [ 1.23379295e-01 -1.38053976e-01  1.34670588e-01  2.84901782e-01
  -4.37660252e-01 -3.38081853e-01  3.39781390e-01 -3.09549498e-01
   1.99635796e-01  1.40976728e-01]
 [-3.49019285e-01 -6.20035145e-02  2.57569342e-01  2.17028164e-01
   5.25480510e-02 -3.28561692e-01 -4.01102518e-02 -1.01888170e-01
   8.44379374e-02  2.69999420e-01]
 [-2.07264155e-01 -5.14151294e-01 -3.91989234e-01 -2.32171503e-01
   4.36025984e-02  4.65479223e-01  2.04776162e-01  2.57453859e-01
   3.92103233e-01 -1.78388900e-02]]


In [ ]:
# Сгенерируйте случаный массив размера mxn и посчитайте объем занимаемой памяти в килобайтах


In [131]:
Z = np.random.randint(low=10, high=100, size=(10, 10), dtype='int64')
print("The memory size: {}".format(Z.size))

The memory size: 100


In [ ]:
# Создайте вектор любой размерности и разверните его в обратном направлении


In [132]:
Z[::-1]

array([[74, 32, 24, 87, 37, 42, 50, 92, 70, 51],
       [51, 30, 99, 10, 59, 15, 88, 82, 59, 59],
       [48, 58, 66, 20, 26, 39, 34, 89, 23, 78],
       [75, 33, 82, 30, 43, 70, 31, 48, 31, 47],
       [74, 69, 98, 65, 77, 83, 62, 56, 11, 37],
       [65, 28, 32, 34, 63, 67, 63, 70, 95, 42],
       [87, 28, 86, 23, 21, 73, 92, 79, 97, 20],
       [77, 59, 59, 15, 97, 45, 96, 32, 87, 91],
       [88, 99, 99, 60, 30, 87, 52, 79, 10, 91],
       [21, 62, 69, 63, 61, 55, 35, 72, 43, 39]])

In [ ]:
# Создайте две матрицы А и В, проверьте равны ли они


In [ ]:
# Создайте матрицу размерности 25х25 и нормализуйте ее


In [133]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-2.43295870e-01  1.31717921e-01  4.17402622e-01 -1.06873907e-01
  -2.14206295e-01 -2.08767540e-01  6.25717054e-01 -1.61001652e-02
  -3.05773650e-01 -7.98201697e-02]
 [ 1.42205745e-01  6.02497845e-02  2.29215901e-01  1.56234920e-01
   2.06932962e-01 -3.39693963e-01 -6.05664132e-01  2.70756625e-01
   2.21649799e-01 -3.41887642e-01]
 [-1.59567471e-01 -2.23819100e-01 -2.59307006e-01 -1.64087196e-01
   2.95676207e-01 -3.02175297e-01  1.64166619e-04  2.00222229e-01
   1.89791016e-01  4.23102451e-01]
 [ 3.50141280e-01 -1.62784155e-01 -3.34025685e-01 -2.25254170e-02
  -3.37883394e-01  1.72095911e-01 -2.33254736e-01  3.01153858e-01
   3.74557379e-01 -1.07475042e-01]
 [ 1.65572748e-01 -2.26218541e-01  4.07395032e-01  2.26918131e-01
   1.48107982e-01  3.74862168e-01 -3.32107059e-01 -1.96390695e-01
  -1.32177294e-01 -4.35962471e-01]]
