## Манипулирование данными

Невозможно что-либо сделать, если мы не умеем манипулировать данными. Две основные операции, которые нам нужно сделать с данными - (i) получить их и (ii) обработать. Нет смысла собирать данные, если мы даже не знаем, как их хранить, поэтому давайте сначала поработаем с синтетическими данными. Мы начнем с torch.tensor. Это основной инструмент для хранения и преобразования данных в torch. Если вы раньше работали с NumPy, вы заметите, что он по своей конструкции очень похож на многомерный массив NumPy. Тем не менее, он даёт несколько ключевых преимуществ. Во-первых, torch.tensor поддерживает асинхронные вычисления на CPU и GPU. Во-вторых, он обеспечивает поддержку автоматического дифференцирования.


In [1]:
import torch

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [3]:
x = torch.arange(12)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([12])
Values: 
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [4]:
xx = torch.Tensor([[x, x**2, x**3] for x in range(12)])
describe(xx)

Type: torch.FloatTensor
Shape/Size: torch.Size([12, 3])
Values: 
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [2.0000e+00, 4.0000e+00, 8.0000e+00],
        [3.0000e+00, 9.0000e+00, 2.7000e+01],
        [4.0000e+00, 1.6000e+01, 6.4000e+01],
        [5.0000e+00, 2.5000e+01, 1.2500e+02],
        [6.0000e+00, 3.6000e+01, 2.1600e+02],
        [7.0000e+00, 4.9000e+01, 3.4300e+02],
        [8.0000e+00, 6.4000e+01, 5.1200e+02],
        [9.0000e+00, 8.1000e+01, 7.2900e+02],
        [1.0000e+01, 1.0000e+02, 1.0000e+03],
        [1.1000e+01, 1.2100e+02, 1.3310e+03]])


In [5]:
torch.Tensor([1])

tensor([1.])

Мы можем получить форму экземпляра tensor через свойство shape.

In [6]:
x.shape, xx.shape

(torch.Size([12]), torch.Size([12, 3]))

Узнать расположен ли он на gpu или cpu можно через специальный аттрибут - device

In [7]:
x.device

device(type='cpu')

Мы используем функцию view, чтобы изменить форму одного (возможно многомерного) массива на другой, который содержит такое же количество элементов. Например, мы можем преобразовать форму нашего векторного вектора x в (3, 4), который содержит те же значения, но интерпретирует их как матрицу, содержащую 3 строки и 4 столбца. Обратите внимание, что, хотя форма изменилась, элементы в x не изменились. Причем количество элементов осталось прежним.

In [8]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.view((2,-1,2)).shape

torch.Size([2, 3, 2])

Указывать каждое измерение вручную достаточно утомительно. К счастью, torch может автоматически выводить одно измерение, учитывая другие. Мы можем указать -1 для измерения, которое мы хотели бы, чтобы torch автоматически выводил. В нашем случае вместо x.view((3, 4)) мы могли бы использовать x.view ((- 1, 4)) или x.view((3, -1)).

In [10]:
x.view((-1, 4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Другие две полезные функции - zeros и ones. Они создают массивы из всех нулей и всех единиц. Они принимают форму создаваемого тензора в качестве параметра

In [11]:
describe(torch.zeros((2,3,4)))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3, 4])
Values: 
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [12]:
describe(torch.ones((2,3,4)))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3, 4])
Values: 
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


## Операции

Обычно мы хотим не только создавать массивы, но и применять к ним функции. Самые простые и полезные из них - это поэлементные функции. Они работают, выполняя одну скалярную операцию над соответствующими элементами двух массивов. 

In [13]:
x = torch.tensor([1., 2., 4., 8.])
y = torch.ones_like(x) * 2
print('x =', x)
print('y =', y)
print('x + y', x + y)
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

x = tensor([1., 2., 4., 8.])
y = tensor([2., 2., 2., 2.])
x + y tensor([ 3.,  4.,  6., 10.])
x - y tensor([-1.,  0.,  2.,  6.])
x * y tensor([ 2.,  4.,  8., 16.])
x / y tensor([0.5000, 1.0000, 2.0000, 4.0000])


Еще больше операций может быть выполненно поэлементно. Например - операции exp

In [14]:
x.exp()

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

В дополнение к поэлементным вычислениям, мы также можем выполнять матричные операции. Например, матричное умножение. Для этого используется функция mm.

In [15]:
x1 = torch.arange(12)
x2 = torch.arange(12)
x3 = torch.arange(12)

In [16]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.mm(x, y.T)

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

Мы также можем объединить несколько тензоров. Для этого нам нужно указать, по какому измерению производить объединение. В приведенном ниже примере объединяются две матрицы по измерению 0 (по строкам) и измерению 1 (по столбцам) соответственно.

In [17]:
torch.cat((x, y), axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [18]:
torch.cat((x, y), dim=1)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

Для получения булевых тензоров можно использовать булевы операторы. Например, можно сравнить два тензора при помощи оператора ==

In [19]:
(x <= y).int()

tensor([[1, 1, 1, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [20]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Суммирование всех элементов тезора дает тензор с одним элементом.

In [21]:
x.sum(dim=1, keepdim=True)

tensor([[ 6],
        [22],
        [38]])

Мы можем преобразовать результат в скаляр в Python, используя функцию item

In [22]:
x.sum().item()

66

Преобразование типов

In [23]:
x.dtype

torch.int64

In [24]:
x.double()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [25]:
x.type('torch.DoubleTensor')

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [26]:
x = torch.tensor([4,5,6,7])
y = 3
x - y

tensor([1, 2, 3, 4])

# Изменение размерности

In [27]:
x.shape

torch.Size([4])

In [28]:
x

tensor([4, 5, 6, 7])

In [29]:
x.unsqueeze(1).shape

torch.Size([4, 1])

In [30]:
x.unsqueeze(2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [31]:
x.unsqueeze(1).shape

torch.Size([4, 1])

In [ ]:
x.unsqueeze(1)

In [ ]:
x.unsqueeze(2).shape

In [ ]:
x.unsqueeze(2)

In [ ]:
x.unsqueeze(2).unsqueeze(1).squeeze().shape

In [32]:
x.T

/var/folders/91/k98801wn6yd0ssq44m34fwlh0000gn/T/ipykernel_68019/2120005694.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3575.)
  x.T


tensor([4, 5, 6, 7])

In [ ]:
x

In [33]:
x.unsqueeze(0).squeeze().shape

torch.Size([4])

#  Транспонирование

In [34]:
x.T

tensor([4, 5, 6, 7])

In [35]:
x.permute(1,0)

RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 1 is not equal to len(dims) = 2

In [36]:
xx = torch.rand((2,3,4))

In [37]:
xx

tensor([[[0.6644, 0.0523, 0.1400, 0.7359],
         [0.6177, 0.8154, 0.3962, 0.9386],
         [0.7724, 0.9588, 0.6598, 0.3044]],

        [[0.0797, 0.3514, 0.4053, 0.0949],
         [0.0887, 0.0062, 0.0535, 0.3824],
         [0.6267, 0.9731, 0.8734, 0.3243]]])

In [38]:
xx.permute(1,2,0)

tensor([[[0.6644, 0.0797],
         [0.0523, 0.3514],
         [0.1400, 0.4053],
         [0.7359, 0.0949]],

        [[0.6177, 0.0887],
         [0.8154, 0.0062],
         [0.3962, 0.0535],
         [0.9386, 0.3824]],

        [[0.7724, 0.6267],
         [0.9588, 0.9731],
         [0.6598, 0.8734],
         [0.3044, 0.3243]]])

In [ ]:
x.sum()

In [ ]:
x.shape

In [ ]:
x.sum(dim=1).shape

In [ ]:
x.sum(dim=1, keepdim=True).shape

In [ ]:
x.sum(dim=0, keepdim=True).shape

## Broadcast 

Выполнять операции можно не только с тензорами одинакового размера, но и разного. Когда их формы различаются, запускается механизм broadcast'а: Сначала элементы копируются соответствующим образом, чтобы два тензора имели одинаковую форму, а затем операции выполняются поэлементно.

In [39]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(4).reshape((1, 4))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2, 3]]))

Поскольку a и b являются матрицами (3x1) и (1x2) соответственно, их формы не совпадают. Torch решает эту проблему путем broadcast'а значений обеих матриц в большую (3x2) матрицу следующим образом: для матрицы a он реплицирует столбцы, для матрицы b он реплицирует строки. После чего запускается операция сложения

In [40]:
a + b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

## Индексирование

Как и в любом другом массиве Python, элементы в тензоре могут быть доступны по их индексу. По традиции первый элемент имеет индекс 0, а диапазоны указываются для включения первого, но не последнего элемента. По этой логике `1: 3` выбирает второй и третий элемент из тензора

In [ ]:
x

In [ ]:
x[1:3, 1:3] # [срез строки, срез столбца]

Мы так же можем изменять значения в тензоре

In [ ]:
x[1:3, 2:3] = 9
x

Если мы хотим присвоить нескольким элементам одно и то же значение, мы просто индексируем все из них (при помощи оператора `:`), а затем присваиваем им значение. Например, `[0:2,:]` обращается к первой и второй строчкам.

In [ ]:
x[0:2, :] = 12
x

## В numpy и назад

In [ ]:
x.numpy()

In [ ]:
y = torch.tensor(x.numpy())
y

## Практика

1. Создайте случайный тензор размерности (7,7):

2. Определите операцию матричного умножения на тензоре с шага 1 с любым случайным тензором с размерностью (1, 7):

3. Найдите максимум, минимум и среднее значение для полученного тензора (шаг 2):

4. Найдите индекс максимального и минимального значения для тензора, полученного в шаге 2:

5. Найдите обратную матрицу (тензор), для матрицы (тензора) полученного на шаге 2: