## Введение во фреймворк PyTorch

**PyTorch** - оптимизированная библиотека для работы с тензорами, включающая набор пакетов для глубокого обучения. Основное понятие этой библиотеки - тензор (Tensor).
Тензор - математический объект для хранения многомерных данных.

Как мы видели в презентации тензор ранга 0 - это просто число или скаляр. Тензор ранга 1 - вектор, и аналогично тензор ранга 2 - матрица и тензор ранга n - n-мерный массив скалярных значений.

-------
Установка PyTorch:

Установка осущетсвляется либо просто при помощи пакетного менеджера Pip/conda при помощи команды:

```pip install torchvision -c pytorch```

Но лучше заходить на официальный сайт фреймворка, выбирать свою спецификацию и выполнять установку предложенной коммандой.

[Сайт фреймворка:](https://pytorch.org/)


```pip3 install torch torchvision torchaudio```




# Создание Тензоров

Тензор - фундаментальный объект фреймворка PyTorch и всего глубокого обучения. Задача тензоров - представить данные в числовом виде, чтобы их можно было бы использовать для обучения моделей машинного обучения или моделей нейронных сетей. Например RGB картинка может быть представленна в виде тензора с размерностью [3, 224, 224] где [color_channel, height, width], так как картинка имеет 3 цветовых канала (красный, зеленый и синий), высоту и ширину равную 224 пикселям.

In [2]:
# Опишем функцию которая будет просто выводить информацию об объекте, чтобы не захламлять ненужным кодом ноутбук
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

При помощи PytTytorch можно создавать тензоры множеством способов. Один из них состоит в том, чтобы задать для тензора случайные значения, просто указав нужные размерности:

[Тензор и операции с тензорами, официальная документация.](https://pytorch.org/docs/stable/tensors.html)

In [3]:
import torch
print(torch.__version__)

2.0.1


#### Создание тензоров

In [4]:
# torch.Tensor -> alias for torch.FloatTensor
x_tensor = torch.Tensor(2, 3)
describe(x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Scalar

In [5]:
scalar = torch.tensor(7)
describe(scalar)

Type: torch.LongTensor
Shape/Size: torch.Size([])
Values: 
7


In [6]:
# object's dimension
scalar.ndim

0

In [7]:
# Get tensor back as Python's int object
scalar.item()

7

#### Vectors:

In [8]:
vector = torch.tensor([42, 24])
describe(vector)

Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: 
tensor([42, 24])


In [9]:
vector.ndim

1

#### Matrix:

In [10]:
matrix = torch.tensor([
    [22, 0, 12],
    [13, 21, 22],
    [44, 32, 21]
])

In [11]:
describe(matrix)

Type: torch.LongTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[22,  0, 12],
        [13, 21, 22],
        [44, 32, 21]])


In [12]:
matrix.ndim

2

#### Tensor:

In [13]:
tensor = torch.tensor([
    [
        [3, 6, 9, 10],
        [11, 22, 33, 22],
        [22, 32, 22, 11]
    ],
    [
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
    ],
    [
        [1, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 1, 1, 0],
    ],
    [
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
    ],
    [
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
    ],
])

In [14]:
describe(tensor)

Type: torch.LongTensor
Shape/Size: torch.Size([5, 3, 4])
Values: 
tensor([[[ 3,  6,  9, 10],
         [11, 22, 33, 22],
         [22, 32, 22, 11]],

        [[ 0,  0,  0,  1],
         [ 0,  0,  0,  1],
         [ 0,  0,  0,  1]],

        [[ 1,  0,  0,  1],
         [ 0,  1,  0,  0],
         [ 0,  1,  1,  0]],

        [[ 0,  0,  0,  1],
         [ 0,  0,  0,  1],
         [ 0,  0,  0,  1]],

        [[ 0,  0,  0,  1],
         [ 0,  0,  0,  1],
         [ 0,  0,  0,  1]]])


In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([5, 3, 4])

### Создание случайных тензоров:


[Documentation](https://pytorch.org/docs/stable/generated/torch.rand.html)

Можно также создать тензор, инициализируя его случайными значениями из ```равномерного распределения по интервалу [0, 1)``` или ```стандартного нормального распределения```. Знать это важно так как такой способ будет использоваться в последующем для разного рода инициализаций в различных архитектурах нейронных сетей:

In [17]:
x_tensor = torch.rand(2,3) # случайное равномерное распределение
describe(x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.7524, 0.4548, 0.6980],
        [0.7420, 0.7527, 0.6934]])


In [42]:
x_tensor = torch.randn(2,3)
describe(x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-0.7437,  0.3821, -0.9328],
        [-0.1273,  0.5889, -2.2915]])


Можно также создавать тензоры, заполненные одним и тем же скалярным значением. Для создания тензора из нулей или единиц существуют встроенные функции, а для заполнения конкретными значениями можно воспользоваться методом ```fill_()```



Знак подчеркивания в методах объектов PyTorch означает что операция выполняется "на месте", то есть модифицирует данные объекта без создания новых объектов:

In [19]:
# тензор из нулей
zero_like_tensor = torch.zeros(2,3)
describe(zero_like_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
# тензор из 1
ones_like_tensor = torch.ones(2, 3)
describe(ones_like_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [43]:
# заполнение нулевого тензора случайным скалярным значением
zero_like_tensor.fill_(22)
describe(zero_like_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[22., 22., 22.],
        [22., 22., 22.]])


Range in Tensors:

In [46]:
# torch.range(2, 15)
range_tensor = torch.arange(0, 10)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
another_range_tensor = torch.arange(start=1, step=2, end=22)
another_range_tensor

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [48]:
# creating tensors like
nills = torch.zeros_like(input=another_range_tensor)
nills

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

У нас также есть возможность создавать тензоры декларативным образом, то есть используя уже заранее готовый список данных либо NumPy массив:

! **Тензор PyTorch всегда можно преобразовать в массив numpy и наоборот, будьте внимательны с типом данных, в случае создания тензора из массива numpy типом данных будет являться DoubleTensor!**

Возможность преобразования данных из массивов NumPy в тензоры PyTorch и наоборот играет важную роль при работе с унаследованными библиотеками, в которых используются числовые значения в формате NumPy.|

In [49]:
some_array = ([
    [1, 2, 3],
    [4, 5, 6]
])

declarative_tensor = torch.Tensor(some_array)

describe(declarative_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [52]:
import numpy as np

np_array = np.random.rand(3, 5)

tensor_from_np = torch.tensor(np_array)
describe(tensor_from_np)

Type: torch.DoubleTensor
Shape/Size: torch.Size([3, 5])
Values: 
tensor([[0.3412, 0.4621, 0.1891, 0.0411, 0.6706],
        [0.6413, 0.0761, 0.7915, 0.1222, 0.8971],
        [0.0943, 0.5336, 0.0808, 0.2176, 0.6384]], dtype=torch.float64)


In [53]:
np_array.dtype

dtype('float64')

#### Tensor Datatypes

Наиболее часто во время работы над моделями нейронных сетей, вы будете сталкиваться с 3 наиболее распространнеными ошибками в коде:
1. Tensors are not right datatype
2. Tensors are not right shape
3. Tensors are not on the right device

In [54]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # e.g. float16, float32, bfloat16, complex32 etc.
                               device=None, # "cuda" or "cpu"
                               requires_grad=False) # for automatic differentiation process
describe(float_32_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([3])
Values: 
tensor([3., 6., 9.])


In [55]:
float_32_tensor.dtype

torch.float32

# Типы и Размер Тензоров

У каждого тензора есть тип и размер. Тип тензора по умолчанию при использовании конструктора torch.Tensor -> torch.FloatTensor.
-----



Также существуют возможности преобразовать тензор в другой тип (float, long, double и т.д.)
Менять тип тензора можно либо при инициализации либо воспользовавшись одним из методов приведения типов.

Всего 2 способа указания типа при инициализации:

1. Непосредственно вызвать конструктор конкретного типа тензора, например FloatTensor или LongTensor
2. Воспользоваться специальным методом torch.tensor() добавив параметр dtype (не путать с конструктором тензора torch.Tensor())

Рассмотрим на примере:

In [56]:
x_tensor = torch.FloatTensor([
    [2, 2, 3, 4],
    [2, 0, 1, 0]
])

describe(x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 4])
Values: 
tensor([[2., 2., 3., 4.],
        [2., 0., 1., 0.]])


In [57]:
# Приведение типа данных тензора
x_tensor = x_tensor.long()
describe(x_tensor)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 4])
Values: 
tensor([[2, 2, 3, 4],
        [2, 0, 1, 0]])


In [58]:
x_tensor = x_tensor.float()
describe(x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 4])
Values: 
tensor([[2., 2., 3., 4.],
        [2., 0., 1., 0.]])


Для получения информации о размерах измерений объекта-тензора используется аттрибут ```shape``` и метод ```size()``` (Они идентичны).
Помните и берите на вооружение - проверка формы тензора - ваш лучший друг и напарник при отладке моделей и кода PyTorch. :)

In [59]:
x_tensor.size()

torch.Size([2, 4])

In [60]:
x_tensor.shape

torch.Size([2, 4])

In [61]:
x_tensor.dtype

torch.float32

In [62]:
x_tensor.device

device(type='cpu')

# Операции над тензорами

После создания тензоров с ними можно работать так же как и с базовыми типами данных большинства языков программирования.
Унаследована вся арифметическая база:
1. Сложение
2. Вычитание
3. Деление
4. Умножение

[Документация по математическим операциям в PyTorch](https://pytorch.org/docs/stable/torch.html#math-operations)

#### Сложение тензоров

In [63]:
# Сложение тензоров
x_tensor = torch.randn(3, 3)

describe(x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[ 0.1474, -0.4158, -1.6655],
        [-0.1914, -2.0580,  3.2619],
        [ 1.2915,  0.1179,  0.5573]])


In [64]:
# Добавление скаляра к тензору
x_tensor + 42.0

tensor([[42.1474, 41.5842, 40.3345],
        [41.8086, 39.9420, 45.2619],
        [43.2915, 42.1179, 42.5573]])

In [65]:
# сложение 2-х тензоров
sum_of_tensors = torch.add(x_tensor, x_tensor)
describe(sum_of_tensors)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[ 0.2949, -0.8316, -3.3310],
        [-0.3828, -4.1161,  6.5239],
        [ 2.5830,  0.2358,  1.1147]])


In [66]:
describe(x_tensor + x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[ 0.2949, -0.8316, -3.3310],
        [-0.3828, -4.1161,  6.5239],
        [ 2.5830,  0.2358,  1.1147]])


#### Вычитание тензоров

In [67]:
# Subtracting tensor and scalar
x_tensor - 0.1

tensor([[ 0.0474, -0.5158, -1.7655],
        [-0.2914, -2.1580,  3.1619],
        [ 1.1915,  0.0179,  0.4573]])

In [68]:
# Subtracting tensors
x_tensor - x_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Умножение тензоров

In [69]:
x_tensor

tensor([[ 0.1474, -0.4158, -1.6655],
        [-0.1914, -2.0580,  3.2619],
        [ 1.2915,  0.1179,  0.5573]])

In [70]:
# Tensor-Scalar multiplication
torch.mul(x_tensor, 10)

tensor([[  1.4743,  -4.1579, -16.6553],
        [ -1.9140, -20.5804,  32.6194],
        [ 12.9151,   1.1792,   5.5734]])

### [Матричное умножение тензоров](https://pytorch.org/docs/stable/generated/torch.matmul.html)

In [71]:
tensor = torch.tensor([1., 2., 3.])
tensor

tensor([1., 2., 3.])

In [76]:
# Element-wise multiplication
tensor * tensor

tensor([1., 4., 9.])

In [73]:
# Matrix (dot product) multiplication
torch.matmul(tensor, tensor)

tensor(14.)

In [74]:
tensor @ tensor

tensor(14.)

In [75]:
# Only for 2-D (matrix) multiplications
torch.mm(x_tensor, x_tensor)

tensor([[-2.0497,  0.5980, -2.5301],
        [ 4.5785,  4.6997, -4.5764],
        [ 0.8876, -0.7140, -1.4558]])

Дополнительные операции по манипулированию тензорами:

- Операция ```arange``` служит для создания одномерных тензоров заданного размера со значениями представляющими собой арифметическую прогрессию с указанным шагом  (по умолчанию 1). Вне зависимости от глобальных настроек типом по умолчанию возвращаемых arange значений может быть ```LongTensor```
- Операция ```view``` возвращает новый тензор с теми же данными что и прежде, но разной формы.
- Операция ```sum``` возвращает свертку тензора по заданному измерению.
- Операция ```transpose``` транспонирует тензор меняя местами два указанных измерения.

Рассмотрим все на примерах:

In [83]:
# Одномерный массив арифметической прогрессии
x_tensor = torch.arange(6)
describe(x_tensor)

Type: torch.LongTensor
Shape/Size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [84]:
# Изменение формы тензора
x_tensor = x_tensor.view(3, 2) # или x_tensor.view(2, 3) так как всего 6 элементов в тензоре
describe(x_tensor)

Type: torch.LongTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [85]:
# Операция свертки по заданному измерению (в данном случае свертка по столбцам
x_tensor = torch.sum(x_tensor, dim=1)
describe(x_tensor)

Type: torch.LongTensor
Shape/Size: torch.Size([3])
Values: 
tensor([1, 5, 9])


In [86]:
# Операция свертки по заданному измерению (в данном случае свертка по всем значениям (сумма каждого элемента в тензоре)
x_tensor = torch.sum(x_tensor, dim=-1)
describe(x_tensor)

Type: torch.LongTensor
Shape/Size: torch.Size([])
Values: 
15


In [87]:
x_tensor = torch.randn(4, 4)
x_tensor = torch.sum(x_tensor, dim=1)
describe(x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([4])
Values: 
tensor([1.8875, 3.2706, 1.2645, 1.5729])


In [88]:
# Операция транспонирования тензора
x = torch.arange(6).view(2,3)
x = torch.transpose(x, 0, 1)

In [89]:
x.T

tensor([[0, 1, 2],
        [3, 4, 5]])

### Поиск min, max, mean, mode и т.д. (tensor aggregation):

In [90]:
# Random tensor
x = torch.arange(0, 100, 10)

In [91]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [92]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [93]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [94]:
# Find the mean
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [95]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [96]:
# Find the mode
torch.mode(x)

torch.return_types.mode(
values=tensor(0),
indices=tensor(0))

In [97]:
# Find the positional min and max
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [98]:
# find the position in the tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [99]:
x.argmax()

tensor(9)

При работе с фреймворком вам часто придется выполнять над тензорами более сложные операции чем было описано выше, которые включают в себя разнообразные комбинации доступа по индексам, срезы, объединения и перестановка элементов. Как и в библиотеке для вычислений NumPy с которой мы знакомы, в PyTorch также существуют встроенные функции для упрощения подобных операций над тензорами:

#### Обращение по иднексу, срезы и объединение (reshaping, stacking, squeezing and unsqueezing)

- Reshaping - изменение формы тензора к нужней нам размерности (*при наличии возможности)
- Stacking - комбинация нескольких тензоров горизонтально (hstack) либо вертикально (vstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - adds a `1` dimension to a target tensor
- Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [100]:
# Создадим случайный тензор двумерной матрицы размера 2 на 3
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [102]:
# Add an extra dimension
x_reshaped = x.reshape(3, 2)
x_reshaped.shape, x_reshaped.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [103]:
# Change the view
v = x.view(1,6)
v, v.shape

(tensor([[0, 1, 2, 3, 4, 5]]), torch.Size([1, 6]))

In [104]:
# Changing v changes x!!! (because a view of a tensor shares the same memory as the original input)
v[:, 0] = 1
v, x

(tensor([[1, 1, 2, 3, 4, 5]]),
 tensor([[1, 1, 2],
         [3, 4, 5]]))

In [105]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # List of tensors as inputs
x_stacked

tensor([[[1, 1, 2],
         [3, 4, 5]],

        [[1, 1, 2],
         [3, 4, 5]],

        [[1, 1, 2],
         [3, 4, 5]],

        [[1, 1, 2],
         [3, 4, 5]]])

In [106]:
# https://pytorch.org/docs/stable/generated/torch.squeeze.html
# squeeze - removes all single dimensions
x_reshaped, x_reshaped.shape

(tensor([[1, 1],
         [2, 3],
         [4, 5]]),
 torch.Size([3, 2]))

In [107]:
torch.squeeze(x_reshaped,(0,1))

tensor([[1, 1],
        [2, 3],
        [4, 5]])

In [108]:
# torch.unsqueeze() - adds a single dimensiton to a target tensor at a specific dimension
torch.unsqueeze(x_reshaped, 0), torch.unsqueeze(x_reshaped, 0).shape, x_reshaped.shape

(tensor([[[1, 1],
          [2, 3],
          [4, 5]]]),
 torch.Size([1, 3, 2]),
 torch.Size([3, 2]))

In [110]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order (by dims)
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_ch]

# Permute the original tensor to rearrange the axis order
x_permuted = torch.permute(x_original, (2, 0, 1))
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

#### Индексация

#### Indexing (selecting data from tensors). Indexing with PyTorch is similar to indexing with NumPy

In [111]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [112]:
# Indexing
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [114]:
# Index on dim=1
# x[0][0] # or
x[0, 0]

tensor([1, 2, 3])

In [115]:
# Index on the most inner bracker (last dimensions)
x[0][0][0]
# Same
# x[0, 0, 0]

tensor(1)

In [116]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [117]:
# We can also use ":" to select "all" of a target dimension
describe(x[:1, :2])

Type: torch.LongTensor
Shape/Size: torch.Size([1, 2, 3])
Values: 
tensor([[[1, 2, 3],
         [4, 5, 6]]])


In [118]:
describe(x[0,1])

Type: torch.LongTensor
Shape/Size: torch.Size([3])
Values: 
tensor([4, 5, 6])


Сложный доступ по иднексам тензора, обращение по индексам к несмежным участкам тензора:

In [119]:
# https://pytorch.org/docs/stable/generated/torch.index_select.html
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape/Size: torch.Size([1, 2, 3])
Values: 
tensor([[[1, 2, 3],
         [7, 8, 9]]])


In [120]:
indices = torch.LongTensor([0,0])
describe(torch.index_select(x, dim=0, index=indices))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3, 3])
Values: 
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


Тип индексов - LongTensor, так реализован функционал фреймворка. Можно также выполнять объединение тензоров с помощью встроенных функций конкатенации указывая тензоры и нужные измерения:

In [121]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [122]:
# Вертикальная конкатенация (наложение тензоров друг на друга)
describe(torch.cat([x,x], dim=0))

Type: torch.LongTensor
Shape/Size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [123]:
# Горизонтальная конкатенация (построчное слияние двух тензоров в случае одинаковой размерности)
describe(torch.cat([x, x], dim=1))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [124]:
# Соединение двух тензоров -> результат тензор новой размерности
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


#### Операции линейной алгебры над тензорами:

In [125]:
x = torch.arange(6).view(2,3).type(torch.FloatTensor)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [126]:
ones_like_tensor = torch.ones(3, 2)
describe(ones_like_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [127]:
ones_like_tensor[:, 1] += 1
describe(ones_like_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [128]:
# умножение двух тензоров / матриц
describe(torch.mm(x, ones_like_tensor))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


### Tensor to NumPy and vice versa:

In [129]:
# NumPy array to tensor
import numpy as np

np_array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(np_array) # when convering from numpy -> pytorch tensor, pytorch reflects numpy's default datatype of float64
np_array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [130]:
print(tensor.numpy())

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


# PyTorch, тензоры и графы вычислений:
-----




Как и переменные высокоуровневых языков программирования (тот же Python), инкапсулирующие элементы данных и несущие об этих данных дополнительную информацию (в частности адрес ячейки памяти, в которой они хранятся и занимаемые ресурсы памяти), тензоры PyTorch берут на себя все вспомогательные операции необходимые для построения графов вычислений для нужд глубокого обучения. Для этого достаточно установить соответствующий флаг в момент создания тензора.


-----
Класс tensor фреймворка PyTorch инкапсулирует данные (сам тензор) и целый ряд операций таких как алгебраические операции, доступ по индексам и операции изменения формы тензора.
Кроме того, установка дле тензора флага requieres_grad = True делает возможным отслеживание градиента тензора, а заодно и функцию вычисления градиента - оба необходимы для глубокого обучения на основе градиентного спуска (то есть почти всегда).


Рассмотрим несколько примеров:

In [131]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [132]:
print(x.grad)

None


In [133]:
# Опишем любое случайное уравнение чтобы показать работу графа на примере
y = (x + 2) * (x**2 + 5) + 3
describe(y)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)


In [134]:
print(y.grad is None)

True


/var/folders/91/k98801wn6yd0ssq44m34fwlh0000gn/T/ipykernel_54691/2729181402.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:491.)
  print(y.grad is None)


In [135]:
z = y.mean()
describe(z)

Type: torch.FloatTensor
Shape/Size: torch.Size([])
Values: 
21.0


In [136]:
z.backward()
print(x.grad is None)

False


Пояснение:

Когда тензор создается с параметром required_grad=True тем самым PyTorch требуется хранить вспомогательную информацию необходимую для вычисления градиентов. PyTorch будет отслеживать значения получаемые при прямом проходе (forward propagation). Затем в конце вычислений для определения обратного шага (backward propagation) используется одно скалярное значение. Обратный шаг запускается путем вызова метода backward() для тензороа, полученного в результате вычисления функции потерь. При обратном шаге вычисляется значение градиента для объекта-тензора, участвовавшего в прямом проходе.

Градиент представляет с собой значение, отражающее угол наклона выходного значения функции по отношению к ее входному значению. Получить доступ к градиентам можно с помощью переменной экземпляра .grad Она используется для оптимизации и для обновления значений параметров весовых матриц.

# Тензоры CUDA

В вышеуказанных примерах все тензоры и их операции проводились через CPU. При выполнении операций линейной алгебры и тренировки моделей глубокого обучения имеет смысл использовать графический аппаратный ускоритель GPU, который позволит быстрее проводить расчеты и обучение моделей. Если у вас есть GPU компании Nvidia, то имеет смысл пользоваться им. Для применения GPU необходимо сначала выделить под тензор место в памяти GPU. Доступ к GPU производится с помощью API CUDA.

В PyTorch ОБЯЗАТЕЛЬНО необходимо реализовывать проект таким образом, чтобы код не зависел от того есть ли GPU у конечного пользователя или нет (аппаратно независимый подход).

Установка CUDA: https://developer.nvidia.com/cuda-downloads

Первым делом необходимо проверить доступен ли GPU с помомщью torch.cuda.is_available() и извлечь название устройства, вызвав метод torch.device(). Далее необходимо создать все будущие тензоры и переместить их на нужное устройство с помощью метода .to(device).

Пример:

In [137]:
print(torch.cuda.is_available())

False


In [138]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [139]:
x = torch.randn(3, 3).to(device)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[ 0.4285,  0.6008, -1.3636],
        [-0.5294,  1.3846,  0.9059],
        [-0.6370,  0.3545,  0.1056]])


Важное замечание: чтобы работать с CUDA и не-CUDA объектами необходимо убедиться, что они располагаются на одном устройстве. Иначе попытка вычислений обернется ошибкой (CUDA тензоры нельзя соединять с не CUDA).
Чаще всего вышеописанные ситуации возникают при работе с метриками мониторинга вычислений, не включенными в граф вычислений. При работе с двумя объектами-тензорами убедитесь что они располагаются на одном устройстве:

In [ ]:
y = torch.randn(3, 3)
x + y

In [ ]:
cpu_device = torch.device("cpu")
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

Если у вас на машине или сервере несколько GPU устройств, пользуйтесь переменной среды CUDA_VISIBLE_DEVICES:

CUDA_VISIBLE_DEVICES = 0, 1, 2, 3

Немного полезной информации по распрарллеливанию обучения на нескольких GPU:
https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html

## Попрактикуемся и закрепим информацию небольшими упражнениями (Проверяется умение гуглить и закрепленный материал :) )

1. Создайте двумерный тензор, после чего добавьте в него новое измерение размером 1 перед измерением 0:

2. Удалите дополнительное измерение, которое вы создали в шаге 1:

3. Создайте случайный тензор формы 5 на 3 в интервале [3, 7):

4. Создайте тензор со значениями, взятыми из нормального распределения (матожидание = 0, стандартное отклонение = 1):

5. Извлеките индексы всех ненулевых элементов из тензора torch.Tensor([1, 1, 1, 0, 1]):

6. Создайте случайный тензор размерности (3, 1) а затем горизонтально разместите в ряд четыре его копии:

7. Верните пакетное произведение 2 трехмерных матриц (a = torch.rand(3,4,5) и b = torch.rand(3, 5, 4)):

8. Верните пакетное произведение трехмерной и двумерной матриц (a = torch.rand(3, 4, 5) и b = torch.rand(5,4)):